server:
  port: 8889
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhout123456/40_aispringcloud.git
          searchPaths: config
          username: 752074541@qq.com
          password: Zhoutong123456
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/